---
- hosts: servers
  become: yes
  vars_files:
    - group_vars/satellite.yml
    - group_vars/secrets.yml
  gather_facts: no
  
  tasks:
# create dynamic groups to define variables
#    - group_by: 
#        key: "{{ ansible_distribution }}-{{ ansible_distribution_version | truncate(1, True, '') }}"

#    - set_fact: 
#        ak: "{{ ansible_distribution }}-{{ ansible_distribution_version | truncate(1, True, '') }}"

    - name: ":::: Get repos for host ::::"
      include_tasks: roles/satellite-clients/tasks/client_get_enable_repos.yml

#    - name: ":::: Unregister host ::::"
#      include_tasks: ./roles/satellite-clients/tasks/client_unsubscribe.yml
#      vars:
#        satellite: "{{ groups['old_satellite'][0] }}"
    
#    - name: ":::: Register host ::::"
#      include_tasks: ./roles/satellite-clients/tasks/client_unsubscribe.yml
#      vars:
#        satellite: "{{ groups['satellite'][0] }}"
#        activationkey: "{{ groups[ak] }}"
