---
# ansible-satellite | Satellite 6.x Orchestration
- hosts: old_satellite
  become: yes
  vars_files:
    - group_vars/satellite.yml
    - group_vars/secrets.yml
  gather_facts: no

  tasks:
    - name: ":::: Get organizations ::::"
      import_tasks: ./roles/satellite-content/tasks/get_orgs.yml
    
    - name: ":::: Create content inventory ::::"
      include_tasks: ./roles/satellite-content/tasks/create_content_inventory.yml
      with_items: "{{ organizations_list }}"
      vars:
        organization: "{{ item }}"

    - set_fact: 
        inventory_satellite: "{{ inventory_content }}"

    - name: ":::: Get list of all activation keys ::::"
      include_tasks: ./roles/satellite-content/tasks/get_activation_keys_for_org.yml
      with_items: "{{ inventory_satellite }}"
      vars:
        initial_org: "{{ item.organization }}"

    - set_fact: 
        inventory_satellite: "{{ inventory_content }}"

    - name: ":::: Get Host and Key subscriptions ::::"
      include_tasks: ./roles/satellite-content/tasks/get_nodes_for_keys.yml
      with_items: "{{ inventory_satellite }}"
      vars:
        initial_org: "{{ item.activation_key }}"

    - set_fact: 
        inventory_satellite: "{{ inventory_content }}"

    - name: ":::: Create content inventory ::::"
      import_tasks: ./roles/satellite-content/tasks/create_content_inventory.yml 

    - name: ":::: Create content inventory file ::::"
      import_tasks: ./roles/satellite-content/tasks/create_content_inventory_file.yml 

- hosts: satellite6-server-prod
  become: yes
  vars_files:
    - group_vars/satellite.yml
    - group_vars/secrets.yml
  gather_facts: yes
  
  tasks:

     # create dynamic groups to define variables
    - group_by: 
        key: "{{ ansible_distribution }}-{{ ansible_distribution_version | truncate(1, True, '') }}"

    - set_fact: 
        ak: "{{ ansible_distribution }}-{{ ansible_distribution_version | truncate(1, True, '') }}"

    - name: ":::: Unregister host ::::"
      import_tasks: ./roles/satellite-clients/tasks/client_unsubscribe.yml
      vars:
        satellite: "{{ groups['old_satellite'][0] }}"
    
    - name: ":::: Register host ::::"
      import_tasks: ./roles/satellite-clients/tasks/client_unsubscribe.yml
      vars:
        satellite: "{{ groups['satellite'][0] }}"
        activationkey: "{{ groups[ak] }}"
