---
- hosts: servers
  become: yes
  vars_files:
    - group_vars/satellite.yml
    - group_vars/secrets.yml
  gather_facts: yes
  
  tasks:
# create dynamic groups to define variables
#    - group_by: 
#        key: "{{ ansible_distribution }}-{{ ansible_distribution_version | truncate(1, True, '') }}"

    - name: ":::: Get repos for host ::::"
      include_tasks: roles/satellite-clients/tasks/client_get_enable_repos.yml
    
    - name: Copy a new "ntp.conf" file into place, backing up the original if it differs from the copied version
      ansible.builtin.copy:
        src: "/redhat.repo/redhat.repo"
        dest: "/redhat.repo/redhat.repo.{{ ansible_date_time.date }}"
        backup: yes

    - name: ":::: Unregister host ::::"
      include_tasks: ./roles/satellite-clients/tasks/client_unsubscribe.yml
      vars:
        satellite: "{{ groups['old_satellite'][0] }}"
    
    - name: ":::: Register host ::::"
      include_tasks: ./roles/satellite-clients/tasks/client_unsubscribe.yml
      vars:
        satellite: "{{ groups['satellite'][0] }}"

    - name: ":::: Register repos ::::"
      include_tasks: ./roles/satellite-clients/tasks/client_enable_repo.yml
      vars:
        repo: "{{ item }}"
      with_items: "{{ enable_repos_list }}"



