---
# tasks file for satellite-manage-nodes
  # Update certificate
  - name: ":::: Download satellite {{ satellite_server }} certificate ::::"
    shell: 
      cmd: subscription-manager repos --list-enabled
    register: enabled_repos_out

  # Subscribe client
  - name: ":::: Subscribe {{ node }} with activation key ::::"
    community.general.redhat_subscription:
      state: present
      activationkey: "{{ activation_key }}"
      org_id: "{{ organization_id }}"
    register: subscribe_node_out

  # Disable repos