---
# tasks file for satellite-clients

- name: create inventory file
  lineinfile:
    path: "{{ path_vars }}/inventorycontent.yml"
    line: "{{ item.host }} organization={{ organization }} activationkey={{ activationkey }}"
    create: yes
  delegate_to: localhost
  connection: local

- name: create inventory file
  copy: 
    content: "{{ item | to_yaml }}" 
    dest: "{{ path_vars }}/inventory_content.yml"
  delegate_to: localhost
  connection: local
  