---
# Create activation keys

  # Get all activation Keys

- name: ":::: Get Activation Keys for Organization ::::"
  include_tasks: ./get_activation_keys.yml

- name: ":::: Create content inventory ::::"
  include_tasks: ./create_content_inventory.yml
  with_subelements: 
    - "{{ item }}"
    - "{{ activation_keys_list }}"
  vars:
    node:
      "{{ organization }}"
      host: 
      activationkey: "{{ activation_key }}"
      repos: "{{ repos_host }}"

  when: activation_keys_list is defined and (activation_keys_list|length>0)

    


  
    