---
# Create activation keys

  # Get all activation Keys

- name: ":::: Get Activation Keys for Organization ::::"
  include_tasks: ./get_activation_keys.yml

- set_fact: 
    organization: "{{ organization }}"

- name: ":::: Create content inventory ::::"
  include_tasks: ./create_content_inventory.yml
  with_items: "{{ activation_keys_list }}"
  vars:
    activation_key: "{{ item }}"
  when: activation_keys_list is defined and (activation_keys_list|length>0)

    


    