---
# Create activation keys

  # Get all activation Keys

- name: ":::: Get Activation Keys for Organization ::::"
  include_tasks: ./get_activation_keys.yml

- debug:
    msg: "{{ activation_keys_list }}"

- name: ":::: Create content inventory ::::"
  include_tasks: ./create_content_inventory.yml
  with_subelements: "{{ activation_keys_list }}"
  vars:
    node:
      organization: "{{ organization }}"
      host: ""
      activationkey: "{{ item }}"
      repos: ""
  when: activation_keys_list is defined and (activation_keys_list|length>0)

    


  
    