---
# Create activation keys

# Get all nodes for activation Keys
- name: ":::: Get Host and Key subscriptions ::::"
  include_tasks: ./get_nodes_for_key.yml
  with_items: "{{ activation_keys_list }}"
  vars:
    activationkey: "{{ item }}"

    