---
# Create activation keys

  # Get all activation Keys
- name: Get list of all activation keys
  shell:
    cmd: 'hammer activation-key list --organization {{ initial_org }} --fields name'
  register: activation_keys

- set_fact:
    activation_keys_list: "{{  activation_keys.stdout.split('\n') | lower }}"

- set_fact:
    Number_of_keys: "{{ activation_keys_list|length }}"
    activation_keys_list_clean: "{{ activation_keys_list|ansible.utils.remove_keys(matching_parameter= '(s|season)' }}"

- debug:
    msg: 
     - "{{ activation_keys.stdout }}"
     - "{{ activation_keys_list }}"


    


    