---
# tasks file for satellite-clients

- name: Clean old subscription-manager data
  shell: 
    cmd: subscription-manager repos --list-enabled
  register: enable_repos

- debug:
    msg: "{{ enable_repos..stdout.split('\n') | lower }}"

