---
# tasks file for satellite-clients

- name: Get current subscription repositories
  shell: 
    cmd: subscription-manager repos --list-enabled | grep -i 'Repo ID'
  register: enable_repos_id

- name: Get current subscription repositories
  shell: 
    cmd: echo "{{ enable_repos.stdout_lines }}" | awk -F '"' '{print $2}'
  register: enable_repos

- debug:
    msg: "{{ enable_repos.stdout.split('\n') | lower }}"

